<a href="https://colab.research.google.com/github/J4SIB/ai-course-gp/blob/main/lesson7.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [4]:
!python --version


Python 3.12.11


In [13]:
import sys
print(sys.version)

3.12.11 (main, Jun  4 2025, 08:56:18) [GCC 11.4.0]


In [ ]:
!pip freeze

In [17]:
import numpy as np


array = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11 ,12])

print(array)
print(np.shape(array))

array2x6 = array.reshape(2,6)
print(array2x6)

array2x2x3 = array.reshape(2,2,3)
print(array2x2x3)

zagadka = array.reshape(4, -1)
print(zagadka)



[ 1  2  3  4  5  6  7  8  9 10 11 12]
(12,)
[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [18]:
unsorted = np.array([8, 16, 1, -10])

print(unsorted)

sorted = np.sort(unsorted)
print(sorted)

[  8  16   1 -10]
[-10   1   8  16]


In [19]:
unsorted2D = np.array([[7, 2, 9],
 [4, 8, 1],
 [5, 6, 3]])
print(f"Nieposortowana tablica {unsorted2D}")

sorted2D_axis0 = np.sort(unsorted2D,axis=0)
print(f"Tablica posortowana wzdłuż krawędzi 0:\n{sorted2D_axis0}")
sorted2D_axis1 = np.sort(unsorted2D,axis=1)
print(f"Tablica posortowana wzdłuż krawędzi 1:\n{sorted2D_axis1}")

Nieposortowana tablica [[7 2 9]
 [4 8 1]
 [5 6 3]]
Tablica posortowana wzdłuż krawędzi 0:
[[4 2 1]
 [5 6 3]
 [7 8 9]]
Tablica posortowana wzdłuż krawędzi 1:
[[2 7 9]
 [1 4 8]
 [3 5 6]]


In [22]:
players_data = np.array([
 ("Faker", "T1", 5),
 ("TheShy", "Weibo Gaming", 1),
 ("Uzi", "Emerytowany", 0),
 ("Ruler", "JD Gaming", 1),
 ("Doinb", "Emerytowany", 1),
 ("Rekkles", "Los Ratones", 1),
 ("Caps", "G2 Esports", 0)
 ], dtype= [('Nick', 'U30'), ('Team', 'U30'), ('Worlds Title Count', 'i4')])

print(np.sort(players_data, order = 'Nick'))

[('Caps', 'G2 Esports', 0) ('Uzi', 'Emerytowany', 0)
 ('Doinb', 'Emerytowany', 1) ('Rekkles', 'Los Ratones', 1)
 ('Ruler', 'JD Gaming', 1) ('TheShy', 'Weibo Gaming', 1)
 ('Faker', 'T1', 5)]


In [39]:
from numpy import random

for i in range(10):
  print(random.rand()*2-1)


0.8765039636659275
0.18093773667837798
-0.3272853220364371
-0.49916885318865933
-0.5491009373261933
-0.8249831765355622
0.3099688433438268
-0.8470079823745336
-0.5359733166104277
0.6641271590409081


In [42]:
daty = [1241, 972, 1605, 1444, 1683]
print(f"Zbiór dat {daty}")
print(f"Losowa data ze zbioru {random.choice(daty)}")
print(f"Losowe 3 losowe daty ze zbioru: {random.choice(daty, 3)}")

random.shuffle(daty)
print(daty)


Zbiór dat [1241, 972, 1605, 1444, 1683]
Losowa data ze zbioru 1241
Losowe 3 losowe daty ze zbioru: [1444 1241 1241]
[1444, 1683, 1605, 972, 1241]


In [49]:
array = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11 ,12])

print(array[2:5])
print(array[:5])
print(array[5:])
print(array[-3:-1])


[3 4 5]
[1 2 3 4 5]
[ 6  7  8  9 10 11 12]
[10 11]


In [58]:
array2D =np.array( [[1 ,2 , 3, 4 , 5],
                    [6 ,7 , 8, 9, 10],
                    [11, 12, 13, 14, 6]])
print(np.where(array2D % 2))


(array([0, 0, 0, 1, 1, 2, 2]), array([0, 2, 4, 1, 3, 0, 2]))
